"""
ppt_generator.py
Builds a styled .pptx presentation from extracted document text using
python-pptx. Sections: Title, Introduction, Objectives, Methodology,
Results, Conclusion. Content is heuristically extracted from the document.
"""

import re

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# Reuse summarizer/extraction helpers for content sourcing
from utils.summarizer import generate_short_summary, extract_key_findings


def _clean(text):
    return re.sub(r"\s+", " ", text).strip()


def _section_text(text, keywords, max_sentences=4):
    """
    Find sentences relevant to a section by matching section keywords.
    Returns a list of bullet strings.
    """
    sentences = re.split(r"(?<=[.!?])\s+", text)
    bullets = []
    for sent in sentences:
        low = sent.lower()
        if any(k in low for k in keywords) and 5 <= len(sent.split()) <= 35:
            bullets.append(sent.strip())
        if len(bullets) >= max_sentences:
            break
    return bullets


def _fallback_bullets(text, start_frac, end_frac, max_sentences=4):
    """Grab a slice of sentences from a region of the document as bullets."""
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]
    if not sentences:
        return ["Content not available."]
    n = len(sentences)
    seg = sentences[int(n * start_frac):int(n * end_frac)]
    return seg[:max_sentences] if seg else sentences[:max_sentences]


# ---------------------------------------------------------------------------
# Slide styling helpers
# ---------------------------------------------------------------------------
DARK_BG = RGBColor(0x0A, 0x0E, 0x27)
ACCENT = RGBColor(0x00, 0xE5, 0xFF)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)


def _style_background(slide):
    """Apply a dark background fill to a slide."""
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = DARK_BG


def _add_title_slide(prs, title):
    """Create the opening title slide."""
    layout = prs.slide_layouts[6]  # blank layout for full control
    slide = prs.slides.add_slide(layout)
    _style_background(slide)

    box = slide.shapes.add_textbox(Inches(0.8), Inches(2.4),
                                   Inches(8.4), Inches(2.5))
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.alignment = PP_ALIGN.CENTER
    run = p.runs[0]
    run.font.size = Pt(40)
    run.font.bold = True
    run.font.color.rgb = ACCENT

    sub = tf.add_paragraph()
    sub.text = "Generated by ResearchMate AI"
    sub.alignment = PP_ALIGN.CENTER
    sub.runs[0].font.size = Pt(18)
    sub.runs[0].font.color.rgb = WHITE


def _add_content_slide(prs, heading, bullets):
    """Create a content slide with a heading and bullet points."""
    layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(layout)
    _style_background(slide)

    # Heading
    head_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.4),
                                        Inches(9), Inches(1))
    htf = head_box.text_frame
    htf.word_wrap = True
    hp = htf.paragraphs[0]
    hp.text = heading
    hp.runs[0].font.size = Pt(30)
    hp.runs[0].font.bold = True
    hp.runs[0].font.color.rgb = ACCENT

    # Body bullets
    body_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.6),
                                        Inches(8.4), Inches(5))
    btf = body_box.text_frame
    btf.word_wrap = True

    if not bullets:
        bullets = ["Content not available for this section."]

    for i, bullet in enumerate(bullets):
        p = btf.paragraphs[0] if i == 0 else btf.add_paragraph()
        p.text = "• " + bullet
        p.runs[0].font.size = Pt(16)
        p.runs[0].font.color.rgb = WHITE
        p.space_after = Pt(10)


def build_presentation(text, title, out_path):
    """
    Build the full presentation and save to `out_path`.

    Sections are populated from the document using keyword heuristics with
    positional fallbacks so every slide always contains relevant content.
    """
    text = _clean(text)
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)

    # 1. Title slide
    _add_title_slide(prs, title)

    # 2. Introduction (from start of doc + short summary)
    intro = _section_text(text, ["introduc", "background", "this paper",
                                  "this study", "we present"], 4)
    if not intro:
        intro = _fallback_bullets(text, 0.0, 0.15)
    # Prepend a one-line abstractive overview if available
    try:
        overview = generate_short_summary(text)
        if overview:
            intro = [overview] + intro
    except Exception:
        pass
    _add_content_slide(prs, "Introduction", intro[:5])

    # 3. Objectives
    objectives = _section_text(text, ["objective", "aim", "goal", "purpose",
                                       "we propose", "this work aims"], 4)
    if not objectives:
        objectives = _fallback_bullets(text, 0.1, 0.25)
    _add_content_slide(prs, "Objectives", objectives[:5])

    # 4. Methodology
    methodology = _section_text(text, ["method", "approach", "we use",
                                        "experiment", "dataset", "model",
                                        "algorithm", "procedure"], 5)
    if not methodology:
        methodology = _fallback_bullets(text, 0.3, 0.55)
    _add_content_slide(prs, "Methodology", methodology[:5])

    # 5. Results (reuse key-findings extractor)
    try:
        results = extract_key_findings(text, max_points=5)
    except Exception:
        results = []
    if not results:
        results = _fallback_bullets(text, 0.55, 0.8)
    _add_content_slide(prs, "Results", results[:5])

    # 6. Conclusion
    conclusion = _section_text(text, ["conclu", "in summary", "future work",
                                       "we conclude", "overall"], 4)
    if not conclusion:
        conclusion = _fallback_bullets(text, 0.85, 1.0)
    _add_content_slide(prs, "Conclusion", conclusion[:5])

    prs.save(out_path)
    return out_path